import type { Metadata } from "next";
import { Nunito, Manrope } from 'next/font/google'
import "./globals.css";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', "600", '700'], // kerakli og‘irliklar
  variable: '--Family-Nunito', 
});

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', "600", '700'], // kerakli og‘irliklar
  variable: '--Family-Manrope', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${manrope.className}`}>
        {children}
      </body>
    </html>
  );
}
